# Step 3 - This is the test profile. 
# The password is "pass" which is encrypted with the config server's 
# /encrypt endpoint and is decrypted by the server before serving.
example.property= I AM TEST

spring.datasource.url = jdbc:postgresql://database:5432/ostock_dev
spring.datasource.username = postgres
spring.datasource.password = {cipher}22700bbaf83aad39592a72693dcb21c868c3befc86780bec58086841b537672c
